"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/page";
import Sidebar from "@/components/sidebar/page";
import { store } from "@/redux/store";
import { Provider } from "react-redux";
import { useAppSelector } from "@/redux/hooks";
import Loading from "@/components/loading/page";
import { useSearchParams } from "next/navigation";
import { useRouter } from "next/navigation";
import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();

  const isAccountPage = path == "/account";
  console.log(isAccountPage);
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Provider store={store}>
          <div className="navbar">{!isAccountPage && <Navbar />}</div>
          <div className="sided">
            <div className="sideBarContainer">
              {!isAccountPage && (
                <Sidebar sidebarOpen={false} setSidebarOpen={undefined} />
              )}
            </div>
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
